language: php
php:
  - 7.0
  - 7.1
  - 7.2
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - rm composer.lock
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
script:
 - phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
